Added update & install args

diff --git a/yoink b/yoink
--- a/yoink
+++ b/yoink
@@ -1,88 +1,72 @@
-#!/usr/bin/env python3
+#!/bin/bash
 
-import sys, getopt, tarfile
-import os
-from os import path
-class bcolors:
-    HEADER = '\033[95m'
-    BLUE = '\033[94m'
-    CYAN = '\033[96m'
-    GREEN = '\033[92m'
-    WARNING = '\033[93m'
-    FAIL = '\033[91m'
-    ENDC = '\033[0m'
-    BOLD = '\033[1m'
-    UNDERLINE = '\033[4m'
+progs_to_install=()
+progs_shortname=()
+progs_list=()
+source /etc/yoink/mirror
+INSTALL=false
 
-def printColorLine(color,line):
-    print("{0}{1}{2}".format(color,line,bcolors.ENDC))
+function find_packages() {
+	for prog in ${progs_list}; do
+		package_line=`cat /usr/lib/yoink/yoink.db | grep $prog`;
+		if [[ $? -eq 0 ]]; then
+			new_package=`echo $package_line | cut -d ',' -f 2 | tr -d '\r'`;
+			progs_to_install+=("$new_package");
+			progs_shortname+=("$prog");
+		fi
+	done
+}
 
-def extract(tarball,extractOnly):
-    tarball.extractall('/')
-    if extractOnly:
-        tarball.close()
-def doInstallOnly(tarball,installOnly):
-    try:
-        tarball.getmember('./install.sh')
-        tarball.extract('./install.sh','/tmp/')
-    except KeyError:
-        pass
-    if installOnly:
-        tarball.close()
-    if path.exists('/tmp/install.sh'):
-        printColorLine(bcolors.CYAN,"Running install script...")
-        os.system('/bin/bash /tmp/install.sh')
-def doExtraction(package,installOnly,extractOnly,installAll):
-    printColorLine(bcolors.HEADER,"Yoink package: {0}".format(package))
-    yoink_package = None
-    if not path.exists(package):
-        printColorLine(bcolors.FAIL,"Package {0} does not exist!".format(package))
-        exit(1)
-    else:
-        yoink_package = tarfile.open(package)
-        printColorLine(bcolors.GREEN,"Installing {0}...".format(package))
-    if installOnly:
-        doInstallOnly(yoink_package,True)
-        printColorLine(bcolors.GREEN,"Done.")
-        exit(0)
-    if extractOnly:
-        extract(yoink_package,True)
-        printColorLine(bcolors.GREEN,"Done.")
-        exit(0)
-    if installAll:
-        extract(yoink_package,False)
-        doInstallOnly(yoink_package,False)
-        yoink_package.close()
-        printColorLine(bcolors.GREEN,"Done.")
-        exit(0)
+# Downloads the program.
 
-def main(argv):
-    package = ''
-    installOnly = None
-    extractOnly = None
-    installAll = None
+function download_packages() {
+	for i in "${!progs_to_install[@]}"; do
+		echo Downloading ${progs_shortname[$i]} - ${progs_to_install[i]} from $YOINK_MIRROR;
+		program=${progs_to_install[i]};
+		$(wget -q -P /var/cache/yoink "$YOINK_MIRROR/yoinklinux/$program") 2>&1 >/dev/null
+		echo Done.
+	done
+}
 
-    try:
-        opts, args = getopt.getopt(argv,"i:e:a:",["install=","extract=","all="])
-    except:
-        print("yoink [ -i [--install=...], -e [--extract=...], -a [--all=...]]")
-        sys.exit(2)
-    for opt, arg in opts:
-        if opt in ("-i","--install"):
-            installOnly=True
-            package = arg
-            break
-        elif opt in ("-e","--extract"):
-            extractOnly=True
-            package = arg
-            break
-        elif opt in ("-a","--all"):
-            installAll=True
-            package = arg
-            break
-    if package == '':
-        printColorLine(bcolors.FAIL,"You need to supply a package!")
-        exit(1)
-    doExtraction(package,installOnly,extractOnly,installAll)   
-if __name__ == "__main__":
-    main(sys.argv[1:])
+# Installs the program.
+
+function install_packages(){
+	for i in "${!progs_to_install[@]}"; do 
+		tarball=${progs_to_install[i]};
+		/etc/yoink/yoink-pkgr -a /var/cache/yoink/$tarball;
+	done
+}
+
+function yoink_update(){
+	echo "Updating yoink database..."
+	$(wget -q -P /etc/yoink/ "$YOINK_MIRROR/yoinklinux/yoink.db") 2>&1 > /dev/null
+	echo "Done."
+}
+export -f find_packages
+export -f download_packages
+export -f install_packages
+export -f yoink_update
+
+while [[ $# -gt 0 ]] ; do
+	opt="$1"
+	shift;
+	case "$opt" in
+		"update")
+			yoink_update
+			exit 0
+		;;
+		"install")
+			progs_list=$@
+			echo "New progs_list: $progs_list"
+			INSTALL=true
+		;;
+		*)
+			echo "Invalid option."
+			exit 1
+	esac
+	if [[ $INSTALL ]]; then
+		find_packages
+		download_packages
+		install_packages
+	fi
+done
