rewrite yoink-pkgr to bash

diff --git a/yoink-pkgr b/yoink-pkgr
--- a/yoink-pkgr
+++ b/yoink-pkgr
@@ -1,88 +1,49 @@
-#!/usr/bin/env python3
+#!/bin/bash
 
-import sys, getopt, tarfile
-import os
-from os import path
-class bcolors:
-    HEADER = '\033[95m'
-    BLUE = '\033[94m'
-    CYAN = '\033[96m'
-    GREEN = '\033[92m'
-    WARNING = '\033[93m'
-    FAIL = '\033[91m'
-    ENDC = '\033[0m'
-    BOLD = '\033[1m'
-    UNDERLINE = '\033[4m'
+package_list=()
 
-def printColorLine(color,line):
-    print("{0}{1}{2}".format(color,line,bcolors.ENDC))
+function check_file(){
+    file="$1"
+    { tar tvf "$file" .TREE ;} 2> /dev/null
+    tree_status=$?
+    if [[ "$tree_status" -ne 0 ]]; then
+            echo "Package $file does not have a .TREE file? What are you doing?"
+            exit 1
+    fi
+}
 
-def extract(tarball,extractOnly):
-    tarball.extractall('/')
-    if extractOnly:
-        tarball.close()
-def doInstallOnly(tarball,installOnly):
-    try:
-        tarball.getmember('./install.sh')
-        tarball.extract('./install.sh','/tmp/')
-    except KeyError:
-        pass
-    if installOnly:
-        tarball.close()
-    if path.exists('/tmp/install.sh'):
-        printColorLine(bcolors.CYAN,"Running install script...")
-        os.system('/bin/bash /tmp/install.sh')
-def doExtraction(package,installOnly,extractOnly,installAll):
-    printColorLine(bcolors.HEADER,"Yoink package: {0}".format(package))
-    yoink_package = None
-    if not path.exists(package):
-        printColorLine(bcolors.FAIL,"Package {0} does not exist!".format(package))
-        exit(1)
-    else:
-        yoink_package = tarfile.open(package)
-        printColorLine(bcolors.GREEN,"Installing {0}...".format(package))
-    if installOnly:
-        doInstallOnly(yoink_package,True)
-        printColorLine(bcolors.GREEN,"Done.")
-        exit(0)
-    if extractOnly:
-        extract(yoink_package,True)
-        printColorLine(bcolors.GREEN,"Done.")
-        exit(0)
-    if installAll:
-        extract(yoink_package,False)
-        doInstallOnly(yoink_package,False)
-        yoink_package.close()
-        printColorLine(bcolors.GREEN,"Done.")
-        exit(0)
+function install_packages(){
+    for package in "${package_list}"; do
+        check_file "$package"
+        echo "Installing package from $package"
+        tar xf $package -C /
+    done
+}
 
-def main(argv):
-    package = ''
-    installOnly = None
-    extractOnly = None
-    installAll = None
+while [[ $# -gt 0 ]]; do
+    opt="$1"
+    shift;
+    case "$opt" in
+            "install")
+                package_list=$@
+                INSTALL=true
+                break
+                ;;
+            "extract")
+                echo "Method stub."
+                break
+                ;;
+            *)
+                echo "Invalid option."
+                exit 1
+                ;;
+    esac
+done
 
-    try:
-        opts, args = getopt.getopt(argv,"i:e:a:",["install=","extract=","all="])
-    except:
-        print("yoink [ -i [--install=...], -e [--extract=...], -a [--all=...]]")
-        sys.exit(2)
-    for opt, arg in opts:
-        if opt in ("-i","--install"):
-            installOnly=True
-            package = arg
-            break
-        elif opt in ("-e","--extract"):
-            extractOnly=True
-            package = arg
-            break
-        elif opt in ("-a","--all"):
-            installAll=True
-            package = arg
-            break
-    if package == '':
-        printColorLine(bcolors.FAIL,"You need to supply a package!")
-        exit(1)
-    doExtraction(package,installOnly,extractOnly,installAll)   
-if __name__ == "__main__":
-    main(sys.argv[1:])
+[[ $INSTALL ]] && install_packages
+
+
+
+
+
+
